import Head from 'next/head'
import Link from 'next/link'

export default function Home() {
  return (
    <>
      <Head>
        <title>Next Test App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="text-center p-2 mt-10">
          <Link href="/images" className='text-black p-2 border border-solid border-black rounded-sm'>Enter Site</Link>
        </div>
      </main>
    </>
  )
}
